### PR TITLE
:bug: fix AngularFormlyAdapter for drf_auto_endpoint

### PR DESCRIPTION
**Pull request by nanuxbe**
This should fix the expected output for formly, can you please check and validate @adrienbrunet ?

### CODE REVIEW

**Comment by adrienbrunet** [comment]
It's ok for me. Maybe the tests need to be updated for that change. What do you think?

**Comment by nanuxbe** [comment]
Yes, I'm trying to make the tests pass on tox on master before rebasing

**Comment by adrienbrunet** [comment]
You're wonderful :sparkles:

**Comment by nanuxbe** [comment]
Thanks :-)

**Pull request merged**
